language: python

branches: master

notifications:
  email:
    on_failure: never

install:
  - pip install -r requirements.txt
  - npm install -g markdownlint-cli

script:
  - mkdocs build --verbose --clean --strict
  - find . -name \*.md | xargs markdownlint -c .markdownlint-format

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
