language: python

branches: master

notifications:
  email:
    on_failure: never

install:
  - pip install -r requirements.txt
  - npm install -g markdownlint-cli

jobs:
  include:
    - stage: "Static Site Generation"
      name: "mkdocs build"
      script: mkdocs build --verbose --clean --strict
    - stage: "Documentation Test"
      name: "Markdown Linter"
      script: markdownlint -c markdownlint.json *.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
