title: "NIWC Pacific Unmanned Systems and Robotics Publications"
description: "An archive of unmanned systems and robotics papers from U.S. Navy Information Warfare Center (NIWC) Pacific"
baseurl: /Publications
markdown: CommonMarkGhPages
future: true
plugins:
    - jekyll-seo-tag
-gems:
    - jekyll-seo-tag
