site_name: NIWC Pacific Unmanned Systems and Robotics
site_url: https://github.com/niwcpac/publications
site_description: An archive of unmanned systems and robotics papers from U.S. Navy Information Warfare Center (NIWC) Pacific

repo_name: niwcpac/publications
repo_url: https://github.com/niwcpac/publications

theme: material

# Allow accordion (expand/collapse) sections: https://facelessuser.github.io/pymdown-extensions/extensions/details/
markdown_extensions:
  - pymdownx.details

plugins:
  - search

# https://stackoverflow.com/questions/69237778/how-to-embed-a-local-pdf-file-in-mkdocs-generated-website-on-github-pages
# markdown_extensions:
#   - pymdownx.pathconverter:
#       base_path: 'https://github.com/niwcpac/publications' # default: ''
#       relative_path: '' # default ''
#       absolute: true # default: false
