---
name: Publish Site

on:  # NOLINT
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  pages:
    name: Publish Documentation to Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
